run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
