apiVersion: v1
kind: Service
metadata:
  name: spf-server
  namespace: spf
  labels:
    app: spf-server
spec:
  type: ClusterIP
  selector:
    app: spf-server
  ports:
    - name: http
      port: 8080
      targetPort: http
